### ISSUE TITLE
Missing C++11 option

### ISSUE THREAD

**Issue by corna** [MarekPikula/xournalpp#13]
I tried to build your string_new branch but it failed with lots of warnings like this one

```
 /tmp/xournalpp1/src/util/StringUtils.h:98:19: warning: variadic templates only available with -std=c++11 or -std=gnu++11
   template<typename... Args>
                    ^
```

and some errors like this one

```
 /tmp/xournalpp1/src/util/Util.cpp:48:14: error: ‘to_string’ is not a member of ‘std’
   p /= CONCAT(std::to_string(getPid()), ".xoj");
               ^
```

Running make VERBOSE=1 shows that cmake does not run g++ with the C++11 features enabled.
Adding 

```
 target_compile_features(xournalpp-core PRIVATE cxx_variadic_templates)
```

to src/CMakeLists.txt and

```
 target_compile_features(util PRIVATE cxx_variadic_templates)
```

to src/util/CMakeLists.txt solved the problems, but it doesn't seem to me a clean solution. (I just copy-pasted it from [stackoverflow](https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake))
Any better idea?
I'm on Debian Stretch with CMake v3.2.2 and gcc v5.2.1 (Debian 5.2.1-16).

**Comment by MarekPikula** [comment]
I'm working on it right now. C++11 check was working before, so some recent change messed something up.

**Comment by MarekPikula** [comment]
Fixed with latest commit

**Comment by corna** [comment]
Now Xournal++ builds successfully, but Boost still fails with lots of C++11 warnings

```
 ./boost/container/scoped_allocator.hpp:1325:33: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template < typename T, class ...Args>
                                  ^
```

if BUILD_BOOST=ON
